fin = open("/home/vidya/PycharmProjects/pythonProject/Python and Go excrise.docx", "r")
data = fin.read()
occurrences = data.count("Db2")
data = data.replace('Db2','db2')
fin.close()
fin = open("/home/vidya/PycharmProjects/pythonProject/Python and Go excrise.docx", "w")
fin.write(data)
fin.close()
fin = open("/home/vidya/PycharmProjects/pythonProject/Python and Go excrise.docx", "r")
data1 = fin.read()
print(data1)